services:
  pizza-calculator:
    image: ghcr.io/stephenjoly/pizza-calculator/pizza-calculator:__DEPLOY_WIZARD_IMAGE_TAG__
    pull_policy: always
    restart: unless-stopped
    env_file:
      - /home/stephen/docker/appdata/pizza-calculator/staging.env
    ports:
      - 80:80
