services:
  pizza-calculator:
    ports:
      - 80:80
    restart: unless-stopped
    image: ghcr.io/stephenjoly/pizza-calculator/pizza-calculator:local-20260331002726
    pull_policy: always
    env_file:
      - /home/stephen/docker/appdata/pizza-calculator/staging.env
